# PIRRLE CONFIG
# Subconscious Exploitation Conig
temp: 1.0
top_p: 1
frequency_penalty: 0.1
presence_penalty: 0.1 
max_query: 100
max_tokens: 256

# Echoprixia Optimization Conig
search_method: "greedy"
topk: 32
batch_size: 32
num_steps: 10
selective_position: 100
prompt_len: 150
init_strategy: "repeat&complete"
rta_coef: 0.0
head_ce_coef: 4.0
tail_ce_coef: 4.0
loss_type: "CE"
max_prompt_num: 1
force_mutate_ratio: 1.0
jailbreaking_threshold: 0.9
overlapping_threshold: 0.5
candidate_type: "mix"
init_target_len: 100
judge_model: "ensemble"
judge_model_filepath: {"gptfuzz": "hubert233/GPTFuzz",
                      "jailbroken": "/data/guangyu_shen/tdc_llm/ripple/data/cls/evaluator",
                      "tdc": "TDC2023/Llama-2-13b-chat-cls-test-phase"}
early_stop: True
model_filepath: "/data/public_models/llama_v2_chat/Llama-2-7b-chat-hf"
seed: 42
parsing_method: "auto"
